require('./config/environment');
const express=require('express'),helmet=require('helmet'),cors=require('cors'),compression=require('compression'),requestId=require('./middleware/requestId'),errorHandler=require('./middleware/errorHandler'),{apiLimiter}=require('./middleware/rateLimiter'),logger=require('./utils/logger'),app=express();
app.set('trust proxy', 1);
app.use(helmet());
app.use(cors({origin:function(o,cb){if(!o)return cb(null,true);if(o.includes('netlify.app')||o.includes('localhost')||o.includes('127.0.0.1'))return cb(null,true);cb(new Error('CORS'))},methods:['GET','POST','PUT','DELETE','OPTIONS'],allowedHeaders:['Content-Type','Authorization'],credentials:true}));
app.use(compression());app.use(express.json({limit:'10mb'}));app.use(express.urlencoded({extended:true,limit:'10mb'}));app.use(requestId);
app.use((req,res,next)=>{logger.info(`[REQ] ${req.method} ${req.path}`);next()});
app.use('/api',apiLimiter);
app.use('/api/health',require('./routes/health'));
app.use('/api/auth',require('./routes/auth'));
app.use('/api/customers',require('./routes/customers'));
app.use('/api/analytics',require('./routes/analytics'));
app.use('/api/campaigns',require('./routes/campaigns'));
app.use('/api/punch-cards', require('./routes/punchCards'));
app.use('/api/coupons', require('./routes/coupons'));
app.use('/api/raffles', require('./routes/raffles'));
app.use('/api/ai', require('./routes/ai'));
app.use('/api/flash', require('./routes/flash'));
app.use('/api/mystery', require('./routes/mystery'));
app.use('/api/weekly-ad', require('./routes/weeklyAd'));

app.use((req,res)=>res.status(404).json({success:false,error:{code:'NOT_FOUND'}}));
app.use(errorHandler);
module.exports=app;
app.use('/api/ai', require('./routes/shopping'));
